[package]
name = "llama_cpp_low"
version = "0.0.1"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
link-cplusplus = "1.0.9"
log = "0.4.22"
num_cpus = "1.16.0"

[build-dependencies]
bindgen = "0.70.1"
cmake = "0.1.51"

[features]
default = []
cuda = []
