[package]
name = "llama_cpp_low"
version = "0.0.1"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
link-cplusplus = "1.0.9"
log = "0.4.20"
num_cpus = "1.16.0"

[build-dependencies]
bindgen = "0.69.2"
cmake = "0.1.50"

[features]
default = []
cuda = []
sycl = []
sycl_fp16 = []
sycl_nvidia = []
