# doker container with aicirt

FROM vllm/vllm-openai

# install pyaici pre-requisites
RUN pip install posix_ipc ujson

# install pyaici
RUN mkdir /tmp/pyaici
COPY py/setup.py /tmp/pyaici/
COPY py/pyaici /tmp/pyaici/pyaici
RUN cd /tmp/pyaici && pip install . && rm -rf /tmp/pyaici

# patch the vllm python files
COPY target/vllm.tar.gz /tmp/
RUN tar -xzf /tmp/vllm.tar.gz -C /usr/local/lib/python3.10/dist-packages/vllm && rm /tmp/vllm.tar.gz

# install aicirt
COPY target/dist/aicirt/aicirt /usr/bin/aicirt

# copy the controllers
WORKDIR /vllm-workspace
RUN mkdir wasm
COPY target/dist/aici_*.wasm wasm/

# "upload" and tag the controllers
RUN aicirt --module wasm/aici_guidance_ctrl.wasm --tag guidance
RUN aicirt --module wasm/aici_pyctrl.wasm --tag pyctrl --gh-module gh:microsoft/aici/pyctrl
RUN aicirt --module wasm/aici_jsctrl.wasm --tag jsctrl --gh-module gh:microsoft/aici/jsctrl

# not sure about --enforce-eager
ENTRYPOINT ["python3", "-m", "vllm.entrypoints.openai.api_server", "--enforce-eager", "--use-v2-block-manager", "--enable-chunked-prefill", "--aici-rt=/usr/bin/aicirt"]
