# type stubs
from __future__ import annotations
from typing import Sequence
import aici

def register(cb: aici.AiciCallbacks): ...

def tokenize(text: bytes | str) -> list[int]: ...

class TokenSet(Sequence[bool]):
    def __init__(self): ...
    def __getitem__(self, i: int) -> bool: ...
    def __len__(self) -> int: ...
    def set_all(self, value: bool): ...
