name: AICIrt release

on:
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: rustup target add wasm32-wasip1
      - uses: hendrikmuhs/ccache-action@v1.2
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Release script
        run: ./scripts/release.sh --xz
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: target/dist/README.md
          files: |
            target/dist/*.tar.gz
            target/dist/*.tar.xz
            target/dist/*.wasm
